name: docker-react-ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps
      - name: Check logs
        run: docker logs backend
      - name: Run test suite
        run: docker exec -e CI=true test npm run test
