name: docker-react-ci
on: [push, pull_request]

jobs:
  test_client:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the client Dockerfile.dev
        run: docker  build -t zanebclark/react-test -f ./client/Dockerfile.dev ./client
      - name: Check running containers
        run: docker ps
      - name: Run test suite
        run: docker run -e CI=true zanebclark/react-test npm run test
